version: "3.9"
services:
  api:
    build: ./api
    container_name: caseiq_api
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=demo
      - PGPORT=5432
      - ES_HOST=http://elasticsearch:9200
    depends_on:
      - redis
      - postgres
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    command: sh -c "npm install && node src/index.js"

  nginx:
    image: nginx:stable-alpine
    container_name: caseiq_nginx
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro

  redis:
    image: redis:7-alpine
    container_name: caseiq_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: caseiq_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: caseiq_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  pgdata:
